import pandas as pd
import numpy as np

class FeatureEngineer:
    def __init__(self):
        self.cat_mappings = {}

    def create_date_features(self, df, date_col='date'):
        """Extracts temporal features from the date column."""
        df[date_col] = pd.to_datetime(df[date_col])
        df['day_of_week'] = df[date_col].dt.dayofweek
        df['quarter'] = df[date_col].dt.quarter
        df['month'] = df[date_col].dt.month
        df['year'] = df[date_col].dt.year
        df['day_of_year'] = df[date_col].dt.dayofyear
        df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
        
        # Simple hardcoded holidays (expand logic if needed)
        # New Years and Christmas as examples
        df['is_holiday'] = df[date_col].apply(lambda x: 1 if (x.month == 1 and x.day == 1) or (x.month == 12 and x.day == 25) else 0)
        
        return df

    def create_lag_features(self, df, target_col='imputed_sales', lags=[1, 7, 14, 28]):
        """Creates lagged versions of the target variable."""
        # We must sort by store, product, and date to ensure lags are valid
        df = df.sort_values(by=['store_id', 'product_id', 'date'])
        
        for lag in lags:
            df[f'lag_{lag}'] = df.groupby(['store_id', 'product_id'])[target_col].shift(lag)
        
        return df

    def create_rolling_features(self, df, target_col='imputed_sales', windows=[7, 14, 28]):
        """Creates rolling mean and std dev features."""
        df = df.sort_values(by=['store_id', 'product_id', 'date'])
        
        for window in windows:
            # We assume data is daily and sorted. 
            # We create a rolling window grouped by series.
            grouped = df.groupby(['store_id', 'product_id'])[target_col]
            
            # Rolling Mean (shifted by 1 to avoid data leakage - using past to predict today)
            df[f'rolling_mean_{window}'] = grouped.transform(lambda x: x.shift(1).rolling(window=window).mean())
            
            # Rolling Std (Volatility)
            df[f'rolling_std_{window}'] = grouped.transform(lambda x: x.shift(1).rolling(window=window).std())
            
        return df

    def encode_categorical(self, df, cols=['store_id', 'product_id', 'category', 'store_type', 'location_tier', 'demand_type']):
        """Label encodes categorical features for tree-based models."""
        for col in cols:
            if col in df.columns:
                df[col] = df[col].astype('category')
                df[f'{col}_encoded'] = df[col].cat.codes
                # Save mapping for later if needed
                self.cat_mappings[col] = dict(enumerate(df[col].cat.categories))
        return df

    def run_pipeline(self, df):
        """Executes the full feature engineering pipeline."""
        df = self.create_date_features(df)
        df = self.create_lag_features(df)
        df = self.create_rolling_features(df)
        df = self.encode_categorical(df)
        
        # Drop rows with NaN values generated by lags (e.g., first 28 days will have NaNs)
        df = df.dropna()
        
        return df

if __name__ == "__main__":
    # Test block
    print("Feature Engineer class ready.")